version: '3.4'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: LibraryDB
    ports:
      - "5432:5432"

  app:
    image: librarymanagementsystem
    build:
      context: .
      dockerfile: LibraryManagementSystem/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=LibraryDB;Username=postgres;Password=yourpassword"
